-- ============================================================
-- Migration: 019 — Ensure newsletters storage bucket exists
-- Created:   2025-05-13
-- Description: Idempotently creates the newsletters bucket if
--              it was not created by migration 015. The bucket
--              is kept private; files are served via signed URLs
--              generated by /api/admin/newsletters/file.
-- ============================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'newsletters',
  'newsletters',
  false,
  20971520,  -- 20 MB
  ARRAY[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- Ensure RLS policies exist (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'newsletters_select_authenticated'
  ) THEN
    CREATE POLICY "newsletters_select_authenticated"
      ON storage.objects FOR SELECT
      TO authenticated
      USING (bucket_id = 'newsletters');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'newsletters_all_service'
  ) THEN
    CREATE POLICY "newsletters_all_service"
      ON storage.objects FOR ALL
      TO service_role
      USING (bucket_id = 'newsletters');
  END IF;
END;
$$;
